#include <stdio.h>

int main() {
    int choice;
    
    printf("#########################\n");
    printf("# Lorem Ipsum generator #\n");
    printf("#########################\n");
    printf("\n");
    printf("Choose how many paragraphs you want to generate\n");
    printf("You can choose between: 5, 10 or 100\n");
    scanf("%d", &choice);
    
    if (choice == 5) {
        printf("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Fusce id velit ut tortor pretium viverra suspendisse potenti nullam. Quis eleifend quam adipiscing vitae proin sagittis nisl rhoncus. Suscipit tellus mauris a diam maecenas sed. Mauris in aliquam sem fringilla ut morbi tincidunt. Aliquet nibh praesent tristique magna sit amet purus. Ut tellus elementum sagittis vitae et leo. Tristique et egestas quis ipsum suspendisse ultrices. Vitae turpis massa sed elementum tempus egestas. Odio euismod lacinia at quis risus sed vulputate odio. Nunc pulvinar sapien et ligula ullamcorper. Pretium quam vulputate dignissim suspendisse in. Odio euismod lacinia at quis risus sed. Purus viverra accumsan in nisl nisi.\n");
        printf("Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat. Nisi lacus sed viverra tellus in hac. Pretium fusce id velit ut tortor pretium. Vitae proin sagittis nisl rhoncus mattis. Sit amet justo donec enim diam vulputate. Lectus quam id leo in vitae turpis. Sed ullamcorper morbi tincidunt ornare massa eget. Eu tincidunt tortor aliquam nulla facilisi. Laoreet sit amet cursus sit amet dictum sit amet. Suscipit adipiscing bibendum est ultricies integer quis auctor elit. Amet luctus venenatis lectus magna. Elementum facilisis leo vel fringilla est. Blandit massa enim nec dui nunc. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Convallis aenean et tortor at risus viverra adipiscing. Amet dictum sit amet justo donec enim. Tellus cras adipiscing enim eu turpis egestas.\n");
        printf("Enim neque volutpat ac tincidunt vitae semper quis lectus. Egestas congue quisque egestas diam in arcu cursus euismod quis. Sed felis eget velit aliquet sagittis id. Dolor sit amet consectetur adipiscing elit ut aliquam purus sit. Sollicitudin aliquam ultrices sagittis orci. Neque sodales ut etiam sit amet nisl purus. Viverra justo nec ultrices dui sapien eget. Integer quis auctor elit sed vulputate mi. Malesuada proin libero nunc consequat interdum varius sit. Justo nec ultrices dui sapien eget.\n");
        printf("Et sollicitudin ac orci phasellus egestas tellus rutrum tellus pellentesque. Ultricies lacus sed turpis tincidunt id aliquet risus. Mattis pellentesque id nibh tortor id aliquet lectus proin nibh. Lacus luctus accumsan tortor posuere ac ut consequat semper. Tristique senectus et netus et malesuada fames ac turpis egestas. Nibh tortor id aliquet lectus. Metus vulputate eu scelerisque felis imperdiet proin fermentum. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam. Diam maecenas ultricies mi eget mauris pharetra. Malesuada proin libero nunc consequat interdum varius sit amet mattis. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor. Ultrices neque ornare aenean euismod elementum nisi quis. Ultrices eros in cursus turpis. Magna ac placerat vestibulum lectus. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat. Vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Massa placerat duis ultricies lacus sed turpis tincidunt. Tincidunt id aliquet risus feugiat in ante metus. Nunc consequat interdum varius sit amet. Dolor sit amet consectetur adipiscing elit duis tristique.\n");
        printf("Vulputate mi sit amet mauris. Fames ac turpis egestas sed tempus urna. Nisl rhoncus mattis rhoncus urna. Viverra nam libero justo laoreet sit amet cursus sit. Eget mauris pharetra et ultrices. Senectus et netus et malesuada. Quam elementum pulvinar etiam non quam lacus. Aliquam ut porttitor leo a diam sollicitudin. Ut consequat semper viverra nam libero justo laoreet. Congue quisque egestas diam in. Ultrices mi tempus imperdiet nulla. Id nibh tortor id aliquet lectus proin. Quam elementum pulvinar etiam non quam lacus suspendisse faucibus. Aliquet eget sit amet tellus cras adipiscing enim eu. Nunc sed id semper risus in hendrerit gravida rutrum quisque. Ipsum consequat nisl vel pretium lectus quam id. Nisl purus in mollis nunc. Sagittis vitae et leo duis ut. Fringilla est ullamcorper eget nulla. Mollis aliquam ut porttitor leo a.\n");
    }
    
    if(choice == 10) {
        printf("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Scelerisque viverra mauris in aliquam sem fringilla ut. Pellentesque habitant morbi tristique senectus et netus et. Erat imperdiet sed euismod nisi porta lorem mollis aliquam ut. Faucibus scelerisque eleifend donec pretium vulputate. Augue interdum velit euismod in pellentesque. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Donec pretium vulputate sapien nec sagittis aliquam. Blandit cursus risus at ultrices mi tempus imperdiet nulla. Tellus id interdum velit laoreet. In est ante in nibh mauris cursus mattis molestie a. Viverra accumsan in nisl nisi scelerisque eu ultrices. Dictum sit amet justo donec enim diam vulputate ut pharetra. Orci phasellus egestas tellus rutrum tellus pellentesque.\n");
        printf("Ante metus dictum at tempor commodo ullamcorper a lacus. Ipsum a arcu cursus vitae congue mauris. Nibh nisl condimentum id venenatis. Quis viverra nibh cras pulvinar mattis. Scelerisque purus semper eget duis at tellus at urna condimentum. In arcu cursus euismod quis viverra nibh. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices dui. Viverra ipsum nunc aliquet bibendum enim facilisis gravida neque convallis. Quis enim lobortis scelerisque fermentum dui. Fames ac turpis egestas integer eget aliquet. Tincidunt lobortis feugiat vivamus at augue eget. Aliquam nulla facilisi cras fermentum odio.\n");
        printf("Sociis natoque penatibus et magnis. Arcu dictum varius duis at consectetur lorem. Cursus euismod quis viverra nibh. Fringilla ut morbi tincidunt augue interdum velit euismod in pellentesque. Viverra nibh cras pulvinar mattis nunc sed blandit libero. Lectus proin nibh nisl condimentum id venenatis. Sit amet commodo nulla facilisi nullam. Et magnis dis parturient montes nascetur ridiculus. Duis ultricies lacus sed turpis tincidunt. Tellus rutrum tellus pellentesque eu tincidunt tortor. Adipiscing elit ut aliquam purus sit amet. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at augue. Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien. Vulputate sapien nec sagittis aliquam. Nunc sed blandit libero volutpat. Mauris rhoncus aenean vel elit scelerisque. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Ut faucibus pulvinar elementum integer enim neque volutpat ac tincidunt. Quam vulputate dignissim suspendisse in est ante in nibh mauris. Pharetra et ultrices neque ornare aenean euismod.\n");
        printf("Habitant morbi tristique senectus et netus et malesuada fames ac. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Luctus accumsan tortor posuere ac ut consequat semper viverra. Sit amet mattis vulputate enim nulla aliquet porttitor lacus luctus. Mauris commodo quis imperdiet massa tincidunt nunc. Et tortor consequat id porta nibh venenatis cras sed felis. Vestibulum lectus mauris ultrices eros in cursus turpis massa. Risus commodo viverra maecenas accumsan lacus vel. In vitae turpis massa sed elementum. Sagittis orci a scelerisque purus semper eget. Faucibus turpis in eu mi bibendum neque egestas congue. Sed risus pretium quam vulputate dignissim suspendisse. Adipiscing elit pellentesque habitant morbi tristique senectus. Placerat vestibulum lectus mauris ultrices eros.\n");
        printf("Malesuada proin libero nunc consequat interdum varius sit amet mattis. Quis commodo odio aenean sed adipiscing diam. Lectus urna duis convallis convallis tellus id interdum. Nulla pellentesque dignissim enim sit amet venenatis urna cursus eget. Tortor id aliquet lectus proin. Pellentesque nec nam aliquam sem et tortor consequat id porta. Tortor condimentum lacinia quis vel eros donec ac odio tempor. Imperdiet dui accumsan sit amet. Vitae congue eu consequat ac felis donec. Ipsum a arcu cursus vitae congue mauris rhoncus. Volutpat diam ut venenatis tellus in metus vulputate. Est ullamcorper eget nulla facilisi etiam dignissim. Elementum nibh tellus molestie nunc non. Mauris ultrices eros in cursus turpis massa tincidunt. Tincidunt tortor aliquam nulla facilisi cras fermentum odio eu. Congue quisque egestas diam in arcu cursus euismod quis. Maecenas ultricies mi eget mauris.\n");
        printf("Velit euismod in pellentesque massa placerat. Tortor id aliquet lectus proin. Nulla malesuada pellentesque elit eget gravida cum. Sed risus pretium quam vulputate dignissim suspendisse. Vulputate dignissim suspendisse in est. Nisl nunc mi ipsum faucibus vitae aliquet nec. Aliquet risus feugiat in ante metus dictum at tempor. Egestas congue quisque egestas diam in arcu. Dui id ornare arcu odio ut sem nulla. Condimentum mattis pellentesque id nibh. Nam at lectus urna duis convallis convallis tellus id interdum. Nisl condimentum id venenatis a condimentum vitae. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Convallis tellus id interdum velit.\n");
        printf("Tellus mauris a diam maecenas. Ornare aenean euismod elementum nisi quis eleifend quam adipiscing vitae. Metus dictum at tempor commodo ullamcorper a lacus vestibulum. Quam id leo in vitae turpis massa sed. Sagittis nisl rhoncus mattis rhoncus urna neque. Ridiculus mus mauris vitae ultricies leo integer. Lobortis mattis aliquam faucibus purus in. Feugiat sed lectus vestibulum mattis ullamcorper. Fermentum dui faucibus in ornare quam viverra orci sagittis eu. Et magnis dis parturient montes nascetur ridiculus mus. Mi eget mauris pharetra et ultrices neque ornare. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Netus et malesuada fames ac turpis egestas sed tempus urna. Aliquet lectus proin nibh nisl. Vulputate dignissim suspendisse in est ante in nibh mauris cursus. Arcu non sodales neque sodales ut etiam sit amet nisl.\n");
        printf("Sed velit dignissim sodales ut eu sem integer vitae justo. Tellus in metus vulputate eu scelerisque felis imperdiet proin fermentum. Leo vel fringilla est ullamcorper eget nulla facilisi. Id donec ultrices tincidunt arcu non sodales neque. A cras semper auctor neque vitae tempus. Amet consectetur adipiscing elit duis tristique sollicitudin nibh sit amet. Purus sit amet volutpat consequat mauris nunc congue nisi vitae. Sem integer vitae justo eget magna. Dictum fusce ut placerat orci nulla. Eros in cursus turpis massa tincidunt dui ut ornare lectus.\n");
        printf("Eget nunc scelerisque viverra mauris in aliquam sem fringilla ut. At imperdiet dui accumsan sit amet nulla facilisi morbi tempus. Sem fringilla ut morbi tincidunt. Volutpat maecenas volutpat blandit aliquam etiam erat velit scelerisque. Sollicitudin ac orci phasellus egestas tellus rutrum. Mattis ullamcorper velit sed ullamcorper. Nascetur ridiculus mus mauris vitae ultricies leo. Quis enim lobortis scelerisque fermentum dui faucibus in ornare. Elit at imperdiet dui accumsan. Morbi tempus iaculis urna id volutpat. Sapien nec sagittis aliquam malesuada bibendum arcu. Tempor orci eu lobortis elementum nibh. Egestas sed tempus urna et.\n");
        printf("Sem et tortor consequat id porta nibh venenatis. Integer feugiat scelerisque varius morbi enim. Ut porttitor leo a diam sollicitudin tempor id eu. Sit amet nisl suscipit adipiscing bibendum est ultricies integer. Vel risus commodo viverra maecenas. Dui ut ornare lectus sit amet est. Dolor morbi non arcu risus quis varius quam quisque id. Porta nibh venenatis cras sed felis. Tristique senectus et netus et malesuada fames ac turpis. Nec ullamcorper sit amet risus nullam eget. Nisl rhoncus mattis rhoncus urna. Enim facilisis gravida neque convallis. At auctor urna nunc id cursus metus aliquam eleifend mi. Non diam phasellus vestibulum lorem sed risus. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo nec.\n");
    }
}
